name: Build Rust project
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, aarch64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

    - name: Set OpenSSL Environment Variables
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "Setting OpenSSL environment variables"
        echo "OPENSSL_DIR=/usr/lib/ssl" >> $GITHUB_ENV
        echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

    - name: Debug OpenSSL Setup
      run: |
        echo "OpenSSL version:"
        openssl version || echo "OpenSSL not found"
        echo "PKG_CONFIG_PATH:"
        echo $PKG_CONFIG_PATH || echo "PKG_CONFIG_PATH not set"

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.arch }}-unknown-linux-gnu

    - name: Build Project
      run: cargo build --release --target ${{ matrix.arch }}-unknown-linux-gnu

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lobster-rs-${{ matrix.arch }}-${{ matrix.os }}
        path: target/${{ matrix.arch }}-unknown-linux-gnu/release/lobster-rs
